# todo port 번호 8080 사용?
#server:
#  port:



spring:
  #todo RDS 서버 구축하면 변경
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: