# todo port 번호 8080 사용?
#server:
#  port:



spring:
  #todo RDS 서버 구축하면 변경

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://careerupdb.cmlmlcyv4jdw.ap-northeast-2.rds.amazonaws.com:3306/careerup_schema
    username: admin
    password: 12341234
